# Generated by Django 2.1.5 on 2023-01-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230120_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('client_gst', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('room_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_option', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('room_price_day', models.FloatField(blank=True, default=0.0, null=True)),
                ('primary_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_person_address', models.TextField(blank=True, null=True)),
                ('primary_address_data', models.TextField(blank=True, null=True)),
                ('secondary_persons_data', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=100, null=True)),
                ('id_type', models.CharField(blank=True, max_length=25, null=True)),
                ('arrival_dt', models.DateTimeField(blank=True, null=True)),
                ('depature_dt', models.DateTimeField(blank=True, null=True)),
                ('checkintime', models.TimeField(blank=True, null=True)),
                ('checkouttime', models.TimeField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('gst', models.FloatField(blank=True, default=0.0, null=True)),
                ('gst_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('cgst', models.FloatField(blank=True, default=0.0, null=True)),
                ('cgst_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('total', models.FloatField(blank=True, default=0.0, null=True)),
                ('paid_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('total_qty', models.IntegerField(blank=True, null=True)),
                ('bill_data', models.TextField(blank=True, default=0, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_due', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('gst', models.FloatField(blank=True, default=0.0, null=True)),
                ('gst_total', models.FloatField(blank=True, default=0.0, null=True)),
                ('unit_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
