# Generated by Django 2.1.5 on 2023-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_billing_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_1',
            field=models.ImageField(default='enter your image one', upload_to='images/'),
        ),
    ]
