from django.db import models

class project(models.Model):
    name=models.CharField(max_length=30,blank=True, null=True)
    about=models.CharField(max_length=100,blank=True, null=True)
    description=models.TextField(max_length=100,blank=True, null=True)
    actual_price=models.FloatField(max_length=20,blank=True, null=True)
    sale_price=models.FloatField(max_length=100,blank=True, null=True) 
    tax=models.FloatField(max_length=10,blank=True, null=True)
    tax_price=models.FloatField(max_length=10,blank=True, null=True)
    image_1=models.ImageField(upload_to="images/",default="")
    image_2=models.ImageField(upload_to="images/",default="")
    image_3=models.ImageField(upload_to="images/",default="")
    video=models.FileField(upload_to="videos/",default="")
    category=models.CharField(max_length=10,blank=True, null=True)
    features=models.CharField(max_length=100,blank=True, null=True)
    keywords=models.CharField(max_length=50,blank=True, null=True)
    expiry_date=models.DateField(blank=True, null=True)
    quantity=models.IntegerField(max_length=10000,blank=True, null=True)
    product_id=models.IntegerField(max_length=10000,blank=True, null=True)
    diettype=models.CharField(max_length=1000,blank=True, null=True)
    volume=models.CharField(max_length=1000,blank=True, null=True)
    weight=models.IntegerField(max_length=1000,blank=True, null=True)
    specification=models.TextField(max_length=1000,blank=True, null=True)
    minorder=models.CharField(max_length=1000,blank=True, null=True)
    created_by = models.CharField(max_length=255, blank=True, null=True)
    created_dt = models.DateTimeField( blank=True, null=True)
    updated_by = models.CharField(max_length=255, blank=True, null=True)
    updated_dt = models.DateTimeField( blank=True, null=True)
    remark = models.TextField(null=True, blank=True)
    
